'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3649
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Imagenes
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SorteosCAS.Imagenes", GetType(Imagenes).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property barraConcursoFinalizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("barraConcursoFinalizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BarraTitulo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarraTitulo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BolitasQuini4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BolitasQuini4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BordeInferior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordeInferior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BordeInferiorDerecho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordeInferiorDerecho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property bordeInferiorIzquierdo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bordeInferiorIzquierdo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BordeLateral() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordeLateral", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BordeSupDerecho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordeSupDerecho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BordeSupIzquierdo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BordeSupIzquierdo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_ingresar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_ingresar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_ingresar_mouse_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_ingresar_mouse_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_ingresar_seleccionado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_ingresar_seleccionado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_salir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_salir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property boton_salir_mouse_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boton_salir_mouse_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property botonOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property botonseleccionado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("botonseleccionado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnCloseOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnCloseOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnMaximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnMaximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnMaximizeOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnMaximizeOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnMinimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnMinimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BtnMinimizeOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BtnMinimizeOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovalores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovalores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovaloresHora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovaloresHora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovaloresHoraRepetido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovaloresHoraRepetido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovaloresRepetido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovaloresRepetido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovaloresValor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovaloresValor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property campovaloresValorRepetido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("campovaloresValorRepetido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property CANCELAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CANCELAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ckecked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ckecked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property conectar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("conectar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property conSonido() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("conSonido", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property cuadrado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadrado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property cuadradoseleccionado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuadradoseleccionado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DELETE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DELETE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property desconectar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("desconectar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property DOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Eliminado() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Eliminado", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property engranajes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("engranajes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fin_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fin_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fin_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fin_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fin_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fin_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property flechaabajo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flechaabajo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property flechaabajogris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flechaabajogris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property flechacostado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flechacostado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property flechacostadogris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flechacostadogris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondo1sinbarras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo1sinbarras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondo1sinbarras4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo1sinbarras4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FondoBoton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoBoton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FondoBoton2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoBoton2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondoExtraccionesLoterias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoExtraccionesLoterias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondoExtraccionesmasbarras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoExtraccionesmasbarras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondoIniciomasbarras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoIniciomasbarras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondoLiso() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoLiso", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property fondoLisoConBarra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondoLisoConBarra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property FondoLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FondoLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property icalicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icalicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoEjecutar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoEjecutar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoError() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoError", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoOk() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoOk", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoTipoEquipo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoTipoEquipo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoVacio() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoVacio", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property IconoWaitCursor() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("IconoWaitCursor", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ImagenAceptar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagenAceptar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ImagenBuscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagenBuscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ImagenEjecutar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagenEjecutar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ImagenImprimir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagenImprimir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ImagenLimpiar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagenLimpiar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property imp_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property imp_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property imp_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property imp_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property imp_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imp_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property inicio_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property inicio_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property inicio_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property inicio_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property inicio_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inicio_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Interfaces_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Interfaces_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Interfaces_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Interfaces_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Interfaces_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Interfaces_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Interfaces_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Interfaces_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property jur_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jur_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property jur_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jur_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property jur_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jur_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property jur_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jur_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property jur_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jur_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property loading2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property LogoLoteria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoLoteria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property mascota_quini62() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mascota_quini62", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Mensaje_Advertencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensaje_Advertencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Mensaje_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensaje_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Mensaje_Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensaje_Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Mensaje_Pregunta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mensaje_Pregunta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Modificado() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Modificado", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Nuevo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Nuevo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property PasoFabricacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PasoFabricacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property premios_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premios_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property premios_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premios_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property premios_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premios_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property premios_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premios_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property premios_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("premios_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ProcesoFabricacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProcesoFabricacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property ProcesoFabricacionForaneo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProcesoFabricacionForaneo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Producto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Producto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_extension() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_extension", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property pub_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pub_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property resultset_next() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("resultset_next", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property resultset_previous() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("resultset_previous", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Sin_Cambios() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Sin_Cambios", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property SinSonido() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SinSonido", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_Close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_Close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_CloseDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_CloseDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_CloseHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_CloseHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_ClosePressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_ClosePressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_Maximize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_Maximize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MaximizeDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MaximizeDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MaximizeHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MaximizeHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MaximizePressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MaximizePressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_Minimize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_Minimize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MinimizeDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MinimizeDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MinimizeHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MinimizeHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_MinimizePressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_MinimizePressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_Restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_Restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_RestoreDisabled() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_RestoreDisabled", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_RestoreHot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_RestoreHot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Skin_RestorePressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Skin_RestorePressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property sortear_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortear_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property sortear_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortear_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property sortear_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortear_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property sortear_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortear_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property sortear_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sortear_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TEXIT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEXIT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TFIND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TFIND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TGOMA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TGOMA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TipoPersonal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TipoPersonal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TPRINT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TPRINT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property usrFuncion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usrFuncion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property usrFuncionHabilitada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usrFuncionHabilitada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property usrFuncionNoHabilitada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usrFuncionNoHabilitada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property usrRol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usrRol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
