'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3643
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'StronglyTypedResourceBuilder generó automáticamente esta clase
'a través de una herramienta como ResGen o Visual Studio.
'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
'con la opción /str o vuelva a generar su proyecto de VS.
'''<summary>
'''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Mensajes
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SorteosCAS.Mensajes", GetType(Mensajes).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Está seguro que desea revertir todos los cambios realizados?.
    '''</summary>
    Friend Shared ReadOnly Property PreguntaDeshacerCambios() As String
        Get
            Return ResourceManager.GetString("PreguntaDeshacerCambios", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a ¿Desea guardar los cambios antes de salir?.
    '''</summary>
    Friend Shared ReadOnly Property PreguntaGuardarCambios() As String
        Get
            Return ResourceManager.GetString("PreguntaGuardarCambios", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Se revertirán los cambios....
    '''</summary>
    Friend Shared ReadOnly Property TituloDeshacerCambios() As String
        Get
            Return ResourceManager.GetString("TituloDeshacerCambios", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Se eliminarán permanentemente los datos seleccionados....
    '''</summary>
    Friend Shared ReadOnly Property TituloEliminarRegistro() As String
        Get
            Return ResourceManager.GetString("TituloEliminarRegistro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Han ocurrido errores durante la ejecución....
    '''</summary>
    Friend Shared ReadOnly Property TituloErrorGeneral() As String
        Get
            Return ResourceManager.GetString("TituloErrorGeneral", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a No se han guardado los cambios....
    '''</summary>
    Friend Shared ReadOnly Property TituloGuardarCambios() As String
        Get
            Return ResourceManager.GetString("TituloGuardarCambios", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Campo con error....
    '''</summary>
    Friend Shared ReadOnly Property ValidacionCampoErroneo() As String
        Get
            Return ResourceManager.GetString("ValidacionCampoErroneo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Debe completar el campo requerido....
    '''</summary>
    Friend Shared ReadOnly Property ValidacionCampoRequerido() As String
        Get
            Return ResourceManager.GetString("ValidacionCampoRequerido", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Busca una cadena traducida similar a Se han encontrado errores en algunos campos....
    '''</summary>
    Friend Shared ReadOnly Property ValidacionCamposErroneos() As String
        Get
            Return ResourceManager.GetString("ValidacionCamposErroneos", resourceCulture)
        End Get
    End Property
End Class
