'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3655
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.3655.
'
Namespace WSCAS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PgmsorteosBinding", [Namespace]:="http://172.24.72.179/soap/Pgmsorteos")>  _
    Partial Public Class Pgmsorteos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getpgmsorteosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getpremiosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private setsorteadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getPDFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getlineascontrolOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getlineasextractoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getpozosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getpozoestimadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private setExtractoQn6BrOperationCompleted As System.Threading.SendOrPostCallback
        
        Private setExtractoQnlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private setExtractoTomOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SorteosCAS.My.MySettings.Default.SorteosCAS_WSCAS_Pgmsorteos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getpgmsorteosCompleted As getpgmsorteosCompletedEventHandler
        
        '''<remarks/>
        Public Event getpremiosCompleted As getpremiosCompletedEventHandler
        
        '''<remarks/>
        Public Event setsorteadoCompleted As setsorteadoCompletedEventHandler
        
        '''<remarks/>
        Public Event getPDFCompleted As getPDFCompletedEventHandler
        
        '''<remarks/>
        Public Event getlineascontrolCompleted As getlineascontrolCompletedEventHandler
        
        '''<remarks/>
        Public Event getlineasextractoCompleted As getlineasextractoCompletedEventHandler
        
        '''<remarks/>
        Public Event getpozosCompleted As getpozosCompletedEventHandler
        
        '''<remarks/>
        Public Event getpozoestimadoCompleted As getpozoestimadoCompletedEventHandler
        
        '''<remarks/>
        Public Event setExtractoQn6BrCompleted As setExtractoQn6BrCompletedEventHandler
        
        '''<remarks/>
        Public Event setExtractoQnlCompleted As setExtractoQnlCompletedEventHandler
        
        '''<remarks/>
        Public Event setExtractoTomCompleted As setExtractoTomCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getpgmsorteos", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getpgmsorteos(ByVal name As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal origen As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("getpgmsorteos", New Object() {name, origen})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getpgmsorteosAsync(ByVal name As String, ByVal origen As String)
            Me.getpgmsorteosAsync(name, origen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getpgmsorteosAsync(ByVal name As String, ByVal origen As String, ByVal userState As Object)
            If (Me.getpgmsorteosOperationCompleted Is Nothing) Then
                Me.getpgmsorteosOperationCompleted = AddressOf Me.OngetpgmsorteosOperationCompleted
            End If
            Me.InvokeAsync("getpgmsorteos", New Object() {name, origen}, Me.getpgmsorteosOperationCompleted, userState)
        End Sub
        
        Private Sub OngetpgmsorteosOperationCompleted(ByVal arg As Object)
            If (Not (Me.getpgmsorteosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getpgmsorteosCompleted(Me, New getpgmsorteosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getpremios", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getpremios(ByVal name As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal origen As String) As <System.Xml.Serialization.SoapElementAttribute("respuesta")> String
            Dim results() As Object = Me.Invoke("getpremios", New Object() {name, origen})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getpremiosAsync(ByVal name As String, ByVal origen As String)
            Me.getpremiosAsync(name, origen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getpremiosAsync(ByVal name As String, ByVal origen As String, ByVal userState As Object)
            If (Me.getpremiosOperationCompleted Is Nothing) Then
                Me.getpremiosOperationCompleted = AddressOf Me.OngetpremiosOperationCompleted
            End If
            Me.InvokeAsync("getpremios", New Object() {name, origen}, Me.getpremiosOperationCompleted, userState)
        End Sub
        
        Private Sub OngetpremiosOperationCompleted(ByVal arg As Object)
            If (Not (Me.getpremiosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getpremiosCompleted(Me, New getpremiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/setsorteado", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function setsorteado(ByVal name As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("setsorteado", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub setsorteadoAsync(ByVal name As String)
            Me.setsorteadoAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub setsorteadoAsync(ByVal name As String, ByVal userState As Object)
            If (Me.setsorteadoOperationCompleted Is Nothing) Then
                Me.setsorteadoOperationCompleted = AddressOf Me.OnsetsorteadoOperationCompleted
            End If
            Me.InvokeAsync("setsorteado", New Object() {name}, Me.setsorteadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnsetsorteadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.setsorteadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent setsorteadoCompleted(Me, New setsorteadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getPDF", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getPDF(<System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal juego As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal sorteo As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal origen As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("getPDF", New Object() {juego, sorteo, origen})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPDFAsync(ByVal juego As String, ByVal sorteo As String, ByVal origen As String)
            Me.getPDFAsync(juego, sorteo, origen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPDFAsync(ByVal juego As String, ByVal sorteo As String, ByVal origen As String, ByVal userState As Object)
            If (Me.getPDFOperationCompleted Is Nothing) Then
                Me.getPDFOperationCompleted = AddressOf Me.OngetPDFOperationCompleted
            End If
            Me.InvokeAsync("getPDF", New Object() {juego, sorteo, origen}, Me.getPDFOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPDFOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPDFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPDFCompleted(Me, New getPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getlineascontrol", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getlineascontrol(ByVal name As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("getlineascontrol", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getlineascontrolAsync(ByVal name As String)
            Me.getlineascontrolAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getlineascontrolAsync(ByVal name As String, ByVal userState As Object)
            If (Me.getlineascontrolOperationCompleted Is Nothing) Then
                Me.getlineascontrolOperationCompleted = AddressOf Me.OngetlineascontrolOperationCompleted
            End If
            Me.InvokeAsync("getlineascontrol", New Object() {name}, Me.getlineascontrolOperationCompleted, userState)
        End Sub
        
        Private Sub OngetlineascontrolOperationCompleted(ByVal arg As Object)
            If (Not (Me.getlineascontrolCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getlineascontrolCompleted(Me, New getlineascontrolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getlineasextracto", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getlineasextracto(ByVal name As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("getlineasextracto", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getlineasextractoAsync(ByVal name As String)
            Me.getlineasextractoAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getlineasextractoAsync(ByVal name As String, ByVal userState As Object)
            If (Me.getlineasextractoOperationCompleted Is Nothing) Then
                Me.getlineasextractoOperationCompleted = AddressOf Me.OngetlineasextractoOperationCompleted
            End If
            Me.InvokeAsync("getlineasextracto", New Object() {name}, Me.getlineasextractoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetlineasextractoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getlineasextractoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getlineasextractoCompleted(Me, New getlineasextractoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getpozos", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getpozos(ByVal name As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal origen As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("getpozos", New Object() {name, origen})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getpozosAsync(ByVal name As String, ByVal origen As String)
            Me.getpozosAsync(name, origen, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getpozosAsync(ByVal name As String, ByVal origen As String, ByVal userState As Object)
            If (Me.getpozosOperationCompleted Is Nothing) Then
                Me.getpozosOperationCompleted = AddressOf Me.OngetpozosOperationCompleted
            End If
            Me.InvokeAsync("getpozos", New Object() {name, origen}, Me.getpozosOperationCompleted, userState)
        End Sub
        
        Private Sub OngetpozosOperationCompleted(ByVal arg As Object)
            If (Not (Me.getpozosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getpozosCompleted(Me, New getpozosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/getpozoestimado", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function getpozoestimado(ByVal name As String) As <System.Xml.Serialization.SoapElementAttribute("respuesta")> String
            Dim results() As Object = Me.Invoke("getpozoestimado", New Object() {name})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getpozoestimadoAsync(ByVal name As String)
            Me.getpozoestimadoAsync(name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getpozoestimadoAsync(ByVal name As String, ByVal userState As Object)
            If (Me.getpozoestimadoOperationCompleted Is Nothing) Then
                Me.getpozoestimadoOperationCompleted = AddressOf Me.OngetpozoestimadoOperationCompleted
            End If
            Me.InvokeAsync("getpozoestimado", New Object() {name}, Me.getpozoestimadoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetpozoestimadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getpozoestimadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getpozoestimadoCompleted(Me, New getpozoestimadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/setExtractoQn6Br", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function setExtractoQn6Br(<System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal juego As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal sorteo As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal loteria As String, ByVal extracto As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("setExtractoQn6Br", New Object() {juego, sorteo, loteria, extracto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub setExtractoQn6BrAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String)
            Me.setExtractoQn6BrAsync(juego, sorteo, loteria, extracto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub setExtractoQn6BrAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String, ByVal userState As Object)
            If (Me.setExtractoQn6BrOperationCompleted Is Nothing) Then
                Me.setExtractoQn6BrOperationCompleted = AddressOf Me.OnsetExtractoQn6BrOperationCompleted
            End If
            Me.InvokeAsync("setExtractoQn6Br", New Object() {juego, sorteo, loteria, extracto}, Me.setExtractoQn6BrOperationCompleted, userState)
        End Sub
        
        Private Sub OnsetExtractoQn6BrOperationCompleted(ByVal arg As Object)
            If (Not (Me.setExtractoQn6BrCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent setExtractoQn6BrCompleted(Me, New setExtractoQn6BrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/setExtractoQnl", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function setExtractoQnl(<System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal juego As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal sorteo As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal loteria As String, ByVal extracto As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("setExtractoQnl", New Object() {juego, sorteo, loteria, extracto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub setExtractoQnlAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String)
            Me.setExtractoQnlAsync(juego, sorteo, loteria, extracto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub setExtractoQnlAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String, ByVal userState As Object)
            If (Me.setExtractoQnlOperationCompleted Is Nothing) Then
                Me.setExtractoQnlOperationCompleted = AddressOf Me.OnsetExtractoQnlOperationCompleted
            End If
            Me.InvokeAsync("setExtractoQnl", New Object() {juego, sorteo, loteria, extracto}, Me.setExtractoQnlOperationCompleted, userState)
        End Sub
        
        Private Sub OnsetExtractoQnlOperationCompleted(ByVal arg As Object)
            If (Not (Me.setExtractoQnlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent setExtractoQnlCompleted(Me, New setExtractoQnlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://172.24.72.179/cas/WS_sorteos_CAS/WSCAS.php/setExtractoTom", RequestNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS", ResponseNamespace:="http://192.168.127.77/cas/WS_sorteos_CAS")>  _
        Public Function setExtractoTom(<System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal juego As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal sorteo As String, <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")> ByVal loteria As String, ByVal extracto As String) As <System.Xml.Serialization.SoapElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("setExtractoTom", New Object() {juego, sorteo, loteria, extracto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub setExtractoTomAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String)
            Me.setExtractoTomAsync(juego, sorteo, loteria, extracto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub setExtractoTomAsync(ByVal juego As String, ByVal sorteo As String, ByVal loteria As String, ByVal extracto As String, ByVal userState As Object)
            If (Me.setExtractoTomOperationCompleted Is Nothing) Then
                Me.setExtractoTomOperationCompleted = AddressOf Me.OnsetExtractoTomOperationCompleted
            End If
            Me.InvokeAsync("setExtractoTom", New Object() {juego, sorteo, loteria, extracto}, Me.setExtractoTomOperationCompleted, userState)
        End Sub
        
        Private Sub OnsetExtractoTomOperationCompleted(ByVal arg As Object)
            If (Not (Me.setExtractoTomCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent setExtractoTomCompleted(Me, New setExtractoTomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getpgmsorteosCompletedEventHandler(ByVal sender As Object, ByVal e As getpgmsorteosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getpgmsorteosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getpremiosCompletedEventHandler(ByVal sender As Object, ByVal e As getpremiosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getpremiosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub setsorteadoCompletedEventHandler(ByVal sender As Object, ByVal e As setsorteadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class setsorteadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getPDFCompletedEventHandler(ByVal sender As Object, ByVal e As getPDFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPDFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getlineascontrolCompletedEventHandler(ByVal sender As Object, ByVal e As getlineascontrolCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getlineascontrolCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getlineasextractoCompletedEventHandler(ByVal sender As Object, ByVal e As getlineasextractoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getlineasextractoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getpozosCompletedEventHandler(ByVal sender As Object, ByVal e As getpozosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getpozosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub getpozoestimadoCompletedEventHandler(ByVal sender As Object, ByVal e As getpozoestimadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getpozoestimadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub setExtractoQn6BrCompletedEventHandler(ByVal sender As Object, ByVal e As setExtractoQn6BrCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class setExtractoQn6BrCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub setExtractoQnlCompletedEventHandler(ByVal sender As Object, ByVal e As setExtractoQnlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class setExtractoQnlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")>  _
    Public Delegate Sub setExtractoTomCompletedEventHandler(ByVal sender As Object, ByVal e As setExtractoTomCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class setExtractoTomCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
