'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.9148
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSExtractos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSExtractos.IExtractoServicio")>  _
    Public Interface IExtractoServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/ActualizarEstadoSorteo", ReplyAction:="http://tempuri.org/IExtractoServicio/ActualizarEstadoSorteoResponse")>  _
        Function ActualizarEstadoSorteo(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/ActualizarParametrosSorteo", ReplyAction:="http://tempuri.org/IExtractoServicio/ActualizarParametrosSorteoResponse")>  _
        Function ActualizarParametrosSorteo(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/ObtenerPathExtracto", ReplyAction:="http://tempuri.org/IExtractoServicio/ObtenerPathExtractoResponse")>  _
        Function ObtenerPathExtracto(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/setExtracto", ReplyAction:="http://tempuri.org/IExtractoServicio/setExtractoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Sorteos.WSExtractos.Letra))>  _
        Function setExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/eliminarExtracto", ReplyAction:="http://tempuri.org/IExtractoServicio/eliminarExtractoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Sorteos.WSExtractos.Letra))>  _
        Function eliminarExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/ConfirmarOAnularQuinielaSF", ReplyAction:="http://tempuri.org/IExtractoServicio/ConfirmarOAnularQuinielaSFResponse")>  _
        Function ConfirmarOAnularQuinielaSF(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/ObtenerAutoridadesArchivoBoldt", ReplyAction:="http://tempuri.org/IExtractoServicio/ObtenerAutoridadesArchivoBoldtResponse")>  _
        Function ObtenerAutoridadesArchivoBoldt(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/rePublicarExtracto", ReplyAction:="http://tempuri.org/IExtractoServicio/rePublicarExtractoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Sorteos.WSExtractos.Letra))>  _
        Function rePublicarExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IExtractoServicio/reAnularExtracto", ReplyAction:="http://tempuri.org/IExtractoServicio/reAnularExtractoResponse"),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Sorteos.WSExtractos.Letra))>  _
        Function reAnularExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IExtractoServicioChannel
        Inherits WSExtractos.IExtractoServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ExtractoServicioClient
        Inherits System.ServiceModel.ClientBase(Of WSExtractos.IExtractoServicio)
        Implements WSExtractos.IExtractoServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ActualizarEstadoSorteo(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean Implements WSExtractos.IExtractoServicio.ActualizarEstadoSorteo
            Return MyBase.Channel.ActualizarEstadoSorteo(Sorteo)
        End Function
        
        Public Function ActualizarParametrosSorteo(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean Implements WSExtractos.IExtractoServicio.ActualizarParametrosSorteo
            Return MyBase.Channel.ActualizarParametrosSorteo(Sorteo)
        End Function
        
        Public Function ObtenerPathExtracto(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As String Implements WSExtractos.IExtractoServicio.ObtenerPathExtracto
            Return MyBase.Channel.ObtenerPathExtracto(Sorteo)
        End Function
        
        Public Function setExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean Implements WSExtractos.IExtractoServicio.setExtracto
            Return MyBase.Channel.setExtracto(extr)
        End Function
        
        Public Function eliminarExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean Implements WSExtractos.IExtractoServicio.eliminarExtracto
            Return MyBase.Channel.eliminarExtracto(extr)
        End Function
        
        Public Function ConfirmarOAnularQuinielaSF(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As Boolean Implements WSExtractos.IExtractoServicio.ConfirmarOAnularQuinielaSF
            Return MyBase.Channel.ConfirmarOAnularQuinielaSF(Sorteo)
        End Function
        
        Public Function ObtenerAutoridadesArchivoBoldt(ByVal Sorteo As Sorteos.WSExtractos.pgmSorteoDto) As String Implements WSExtractos.IExtractoServicio.ObtenerAutoridadesArchivoBoldt
            Return MyBase.Channel.ObtenerAutoridadesArchivoBoldt(Sorteo)
        End Function
        
        Public Function rePublicarExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean Implements WSExtractos.IExtractoServicio.rePublicarExtracto
            Return MyBase.Channel.rePublicarExtracto(extr)
        End Function
        
        Public Function reAnularExtracto(ByVal extr As Sorteos.WSExtractos.Extracto) As Boolean Implements WSExtractos.IExtractoServicio.reAnularExtracto
            Return MyBase.Channel.reAnularExtracto(extr)
        End Function
    End Class
End Namespace
